FROM node:16-buster as build

# Set working directory
WORKDIR /app

# Copy package files 
COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci --production

COPY . .

# Build the app
RUN npm run build

# Create image based on nginx and deploy our built React app
FROM nginx:1.17-alpine as prod 

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]