version: "3.7"

services:
  react-app:
    image: apnito/raaga:react-dev-latest
    container_name: react-app
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Kolkata"
    volumes:
      - django_static:/usr/share/nginx/html/static
    depends_on:
      - flask-api

  flask-api:
    image: apnito/raaga:flask-dev-latest
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    container_name: django-backend
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Kolkata"
    volumes:
      - django_static:/backend/static
#   postgres:
#     image: postgres
#     environment:
#       POSTGRES_HOST: postgres
#       POSTGRES_DB: raaga
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: raaga
#     container_name: postgres-db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_db_vol:/var/lib/postgresql/data

volumes:
  django_static:
