# Generated by Django 4.1.2 on 2022-10-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumental',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'instrumental',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=6)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField()),
                ('about', models.TextField()),
                ('qualification', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=256)),
                ('achievement', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('class_mode', models.CharField(max_length=7)),
                ('schedule', models.JSONField()),
                ('rating', models.FloatField()),
                ('reviews', models.JSONField()),
                ('like_count', models.IntegerField()),
                ('student_count', models.IntegerField()),
                ('image_url', models.CharField(max_length=50)),
                ('video_url', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vocal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vocal',
                'managed': True,
            },
        ),
    ]
