# Generated by Django 4.1.2 on 2023-05-01 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=36)),
                ('teacher_id', models.CharField(max_length=36)),
                ('teacher_name', models.CharField(max_length=256)),
                ('student_id', models.CharField(max_length=36)),
                ('student_name', models.CharField(max_length=256)),
                ('category_type', models.CharField(max_length=20)),
                ('category_value', models.CharField(max_length=50)),
                ('class_timestamp', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
                ('is_completed', models.BooleanField()),
                ('is_rescheduled', models.BooleanField()),
                ('is_cancelled', models.BooleanField()),
                ('meeting_link', models.CharField(max_length=256)),
                ('payment_id', models.CharField(max_length=36)),
                ('payment_amount', models.IntegerField()),
                ('payment_timestamp', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instrumental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'instrumental',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=6)),
                ('image_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=6)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=256)),
                ('achievement', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('rated_by', models.JSONField(blank=True, default=dict, null=True)),
                ('reviews', models.JSONField(blank=True, default=dict, null=True)),
                ('liked_by', models.JSONField(blank=True, default=list, null=True)),
                ('student_count', models.IntegerField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=256, null=True)),
                ('video_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'teacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vocal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vocal',
                'managed': True,
            },
        ),
    ]
