# Generated by Django 4.1.2 on 2022-10-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='achievement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_mode',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image_url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pin_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='reviews',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='schedule',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='video_url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
