# Generated by Django 4.1.2 on 2022-11-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_teacher_about_alter_teacher_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_mode',
        ),
    ]
