# Generated by Django 4.1.2 on 2022-11-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_teacher_class_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email_id',
            field=models.CharField(max_length=256),
        ),
    ]
