# Generated by Django 4.1.2 on 2022-11-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_teacher_contact_number_alter_teacher_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='group_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='class',
            name='payment_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='class',
            name='student_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='video_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
