# Generated by Django 4.1.2 on 2022-12-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_student_image_url_alter_class_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rating',
        ),
        migrations.AddField(
            model_name='teacher',
            name='liked_by',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rated_by',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='reviews',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
