name: Docker Image CI

on:
  workflow_dispatch:

  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PAT}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the React Docker image and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: ${{secrets.DOCKER_USER}}/raaga:react-dev-latest
      - name: Build the Flask Docker image and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USER}}/raaga:flask-dev-latest
      - name: SCP docker-compose.dev.yml to EC2 instance
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.DEV_EC2_HOST }}
          USERNAME: ${{ secrets.DEV_EC2_USER }}
          PORT: ${{ secrets.DEV_EC2_PORT }}
          KEY: ${{ secrets.DEV_EC2_SSHKEY }}
        with:
          source: "./docker-compose.yml"
          target: "/home/ubuntu"
      - name: running docker compose up using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USER }}
          key: ${{ secrets.DEV_EC2_SSHKEY }}
          port: ${{ secrets.DEV_EC2_PORT }}
          script: |
            sudo docker compose -f docker-compose.yml down
            sudo docker compose -f docker-compose.yml pull && sudo docker compose -f docker-compose.yml up -d
